{
    "openapi": "3.0.2",
    "info": {
        "title": "Pacientes",
        "version": "1.0.0",
        "description": "ProHealth - Contrato da API de Pacientes"
    },
    "servers": [
        {
            "url": "http://localhost:8080",
            "description": ""
        }
    ],
    "paths": {
        "/patients": {
            "summary": "Conjunto de pacientes atendidos pela clinica",
            "description": "Este recurso é a representação dos pacientes que precisam de atendimento médico e, para isso, solicitam marcação de consultas a partir do controle de agendamento da clínica",
            "get": {
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/PatientsResponseList"
                    }
                },
                "summary": "Consulta de pacientes",
                "description": "Operação utilizada para consultar todos os pacientes da clínica"
            },
            "put": {
                "summary": "Atualização de pacientes",
                "description": "Operação utilizada para atualizar dados de pacientes da clínica"
            },
            "post": {
                "requestBody": {
                    "description": "Request para criação de pacientes",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PatientsRequest"
                            },
                            "examples": {
                                "PatientsRequestExample": {
                                    "value": {
                                        "name": "Marcio Andrade",
                                        "cpf": "123.345.789-0",
                                        "phone_number": "11-91111-4394",
                                        "birthdate": "2001-08-10",
                                        "height": {
                                            "value": 1.78,
                                            "unit": "m"
                                        },
                                        "weight": {
                                            "value": 80,
                                            "unit": "kg"
                                        },
                                        "smoker": false,
                                        "comorbidities": [
                                            "Cirrose hepática",
                                            "Valvopatia"
                                        ],
                                        "medical_insurance": {
                                            "id": "324.5231100.3432",
                                            "operator_code": "AMIL"
                                        },
                                        "address": {
                                            "street": "Rua Luis Gois, 1200",
                                            "complement": "apto 204",
                                            "district": "Vila Mariana",
                                            "city": "São Paulo",
                                            "state": "SP",
                                            "zipcode": "04043-050"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "$ref": "#/components/responses/PatientsResponse"
                    }
                },
                "summary": "Criação de pacientes",
                "description": "Operação utilizada para cadastrar novos pacientes da clínica"
            },
            "delete": {
                "summary": "Remoção de pacientes",
                "description": "Operação utilizada para apagar pacientes do cadastro da clínica"
            },
            "patch": {
                "summary": "Atualização de pacientes",
                "description": "Operação utilizada para atualizar dados de pacientes da clínica"
            }
        },
        "/patients/{id}": {
            "summary": "Informações sobre o paciente atendido pela clinica",
            "description": "Este recurso é a representação de cada paciente que precisa de atendimento médico e, para isso, solicita marcação de consultas a partir do controle de agendamento da clínica",
            "get": {
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/PatientsResponse"
                    }
                },
                "summary": "Consulta de dados de um paciente",
                "description": "Operação utilizada para consultar dados de pacientes da clínica"
            },
            "put": {
                "requestBody": {
                    "description": "Request para atualização de pacientes",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PatientsRequest"
                            },
                            "examples": {
                                "PatientsRequestExample": {
                                    "value": {
                                        "id": "3dc97efc-1b5b-492c-905c-449677b390e1",
                                        "name": "Marcio Andrade",
                                        "cpf": "123.345.789-0",
                                        "phone_number": "11-91111-4394",
                                        "birthdate": "2001-08-10",
                                        "height": {
                                            "value": 1.78,
                                            "unit": "m"
                                        },
                                        "weight": {
                                            "value": 80,
                                            "unit": "kg"
                                        },
                                        "smoker": false,
                                        "comorbidities": [
                                            "Cirrose hepática",
                                            "Valvopatia"
                                        ],
                                        "medical_insurance": {
                                            "id": "324.5231100.3432",
                                            "operator_code": "AMIL"
                                        },
                                        "address": {
                                            "street": "Rua Luis Gois, 1200",
                                            "complement": "apto 204",
                                            "district": "Vila Mariana",
                                            "city": "São Paulo",
                                            "state": "SP",
                                            "zipcode": "04043-050"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/PatientsResponse"
                    }
                },
                "summary": "Atualização de dados de um paciente",
                "description": "Operação utilizada para atualizar dados de pacientes da clínica"
            },
            "post": {
                "summary": "Criação de pacientes",
                "description": "Operação utilizada para cadastrar novos pacientes da clínica"
            },
            "delete": {
                "responses": {
                    "204": {
                        "description": "Response para remoção de um paciente"
                    }
                },
                "summary": "Remoção de pacientes",
                "description": "Operação utilizada para apagar um paciente do cadastro da clínica"
            },
            "patch": {
                "requestBody": {
                    "description": "Request para atualização de pacientes",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PatientsRequestPatch"
                            },
                            "examples": {
                                "PatientsRequestExample": {
                                    "value": {
                                        "id": "3dc97efc-1b5b-492c-905c-449677b390e1",
                                        "name": "Marcio Andrade",
                                        "cpf": "123.345.789-0",
                                        "phone_number": "11-91111-4394",
                                        "birthdate": "2001-08-10",
                                        "height": {
                                            "value": 1.78,
                                            "unit": "m"
                                        },
                                        "weight": {
                                            "value": 80,
                                            "unit": "kg"
                                        },
                                        "smoker": false,
                                        "comorbidities": [
                                            "Cirrose hepática",
                                            "Valvopatia"
                                        ],
                                        "medical_insurance": {
                                            "id": "324.5231100.3432",
                                            "operator_code": "AMIL"
                                        },
                                        "address": {
                                            "street": "Rua Luis Gois, 1200",
                                            "complement": "apto 204",
                                            "district": "Vila Mariana",
                                            "city": "São Paulo",
                                            "state": "SP",
                                            "zipcode": "04043-050"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/PatientsResponse"
                    }
                },
                "summary": "Atualização de dados de um paciente",
                "description": "Operação utilizada para atualizar dados de pacientes da clínica"
            },
            "parameters": [
                {
                    "name": "id",
                    "description": "Campo identificador da entidade Pacientes",
                    "schema": {
                        "type": "string"
                    },
                    "in": "path",
                    "required": true
                }
            ]
        }
    },
    "components": {
        "schemas": {
            "Height": {
                "title": "Root Type for Height",
                "description": "Objeto que representa a altura de uma pessoa",
                "required": [
                    "unit",
                    "value"
                ],
                "type": "object",
                "properties": {
                    "value": {
                        "format": "double",
                        "description": "Valor da medida de altura de uma pessoa",
                        "type": "number"
                    },
                    "unit": {
                        "description": "Unidade de medida da altura",
                        "type": "string"
                    }
                },
                "example": {
                    "value": 1.78,
                    "unit": "m"
                }
            },
            "Weight": {
                "title": "Root Type for Weight",
                "description": "Objeto que representa o peso de uma pessoa",
                "required": [
                    "unit",
                    "value"
                ],
                "type": "object",
                "properties": {
                    "value": {
                        "format": "double",
                        "description": "Valor da medida de peso de uma pessoa",
                        "type": "number"
                    },
                    "unit": {
                        "description": "Unidade de medida do peso",
                        "type": "string"
                    }
                },
                "example": {
                    "value": 1.78,
                    "unit": "m"
                }
            },
            "MedicalInsurance": {
                "title": "Root Type for MedicalInsurance",
                "description": "Objeto que representa o plano de saúde de um paciente",
                "required": [
                    "id",
                    "operator_code"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "description": "Código de inscrição do paciente na sua operadora de plano de saúde",
                        "type": "string"
                    },
                    "operator_code": {
                        "description": "Código da operadora de plano de saúde na qual o paciente está inscrito",
                        "type": "string"
                    }
                },
                "example": {
                    "id": "324.5231100.3432",
                    "operator_code": "AMIL"
                }
            },
            "Address": {
                "title": "Root Type for Address",
                "description": "Objeto que representa o endereço residencial do paciente",
                "required": [
                    "city",
                    "district",
                    "state",
                    "street",
                    "zipcode"
                ],
                "type": "object",
                "properties": {
                    "street": {
                        "description": "Nome da rua onde o paciente reside",
                        "type": "string"
                    },
                    "complement": {
                        "description": "Complemento do endereço (ex: apartamento, bloco, etc)",
                        "type": "string"
                    },
                    "district": {
                        "description": "Nome do bairro",
                        "type": "string"
                    },
                    "city": {
                        "description": "Nome da cidade",
                        "type": "string"
                    },
                    "state": {
                        "description": "Nome do estado",
                        "type": "string"
                    },
                    "zipcode": {
                        "description": "Código postal - CEP",
                        "type": "string"
                    }
                },
                "example": {
                    "street": "Rua Luis Gois, 1200",
                    "complement": "apto 204",
                    "district": "Vila Mariana",
                    "city": "São Paulo",
                    "state": "SP",
                    "zipcode": "04043-050"
                }
            },
            "PatientsResponse": {
                "title": "Root Type for PatientsResponse",
                "description": "Representa um paciente da clínica - utilizado no response da consulta do objeto de instância",
                "required": [
                    "address",
                    "birthdate",
                    "cpf",
                    "height",
                    "id",
                    "name",
                    "phone_number",
                    "weight"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "description": "Código único identificador do paciente",
                        "type": "string"
                    },
                    "name": {
                        "description": "Nome completo do paciente",
                        "type": "string"
                    },
                    "cpf": {
                        "description": "Documento de identificação do paciente - CPF",
                        "type": "string"
                    },
                    "phone_number": {
                        "description": "Número de telefone do paciente para contato",
                        "type": "string"
                    },
                    "birthdate": {
                        "format": "date",
                        "description": "Data de nascimento do paciente",
                        "type": "string"
                    },
                    "height": {
                        "$ref": "#/components/schemas/Height",
                        "description": "Altura do paciente",
                        "properties": {
                            "value": {
                                "format": "double",
                                "type": "number"
                            },
                            "unit": {
                                "type": "string"
                            }
                        }
                    },
                    "weight": {
                        "$ref": "#/components/schemas/Weight",
                        "description": "Peso do paciente",
                        "properties": {
                            "value": {
                                "format": "int32",
                                "type": "integer"
                            },
                            "unit": {
                                "type": "string"
                            }
                        }
                    },
                    "smoker": {
                        "description": "Indica se o paciente é fumante (true-Sim, false-Não)",
                        "type": "boolean"
                    },
                    "comorbidities": {
                        "description": "Lista de comorbidades que afetam o paciente (caso tenha)",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "medical_insurance": {
                        "$ref": "#/components/schemas/MedicalInsurance",
                        "description": "Plano de saúde na qual o paciente está inscrito",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "operator_code": {
                                "type": "string"
                            }
                        }
                    },
                    "address": {
                        "$ref": "#/components/schemas/Address",
                        "description": "Endereço residencial do paciente",
                        "properties": {
                            "street": {
                                "type": "string"
                            },
                            "complement": {
                                "type": "string"
                            },
                            "district": {
                                "type": "string"
                            },
                            "city": {
                                "type": "string"
                            },
                            "state": {
                                "type": "string"
                            },
                            "zipcode": {
                                "type": "string"
                            }
                        }
                    }
                },
                "example": {
                    "id": "3dc97efc-1b5b-492c-905c-449677b390e1",
                    "name": "Marcio Andrade",
                    "cpf": "123.345.789-0",
                    "phone_number": "11-91111-4394",
                    "birthdate": "2001-08-10",
                    "height": {
                        "value": 1.78,
                        "unit": "m"
                    },
                    "weight": {
                        "value": 80,
                        "unit": "kg"
                    },
                    "smoker": false,
                    "comorbidities": [
                        "Cirrose hepática",
                        "Valvopatia"
                    ],
                    "medical_insurance": {
                        "id": "324.5231100.3432",
                        "operator_code": "AMIL"
                    },
                    "address": {
                        "street": "Rua Luis Gois, 1200",
                        "complement": "apto 204",
                        "district": "Vila Mariana",
                        "city": "São Paulo",
                        "state": "SP",
                        "zipcode": "04043-050"
                    }
                }
            },
            "PatientsResponseList": {
                "title": "Root Type for PatientsResponse",
                "description": "Representa uma lista de pacientes da clínica - utilizado no response da consulta do objeto de coleção",
                "required": [
                    "cpf",
                    "id",
                    "name"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "description": "Código único identificador do paciente",
                        "type": "string"
                    },
                    "name": {
                        "description": "Nome completo do paciente",
                        "type": "string"
                    },
                    "cpf": {
                        "description": "Documento de identificação do paciente - CPF",
                        "type": "string"
                    }
                },
                "example": {
                    "id": "3dc97efc-1b5b-492c-905c-449677b390e1",
                    "name": "Marcio Andrade",
                    "cpf": "123.345.789-0"
                }
            },
            "PatientsRequest": {
                "title": "Root Type for PatientsResponse",
                "description": "Representa um paciente da clínica - utilizado no request de criação do objeto de instância",
                "required": [
                    "address",
                    "birthdate",
                    "cpf",
                    "height",
                    "name",
                    "phone_number",
                    "weight"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "description": "Nome completo do paciente",
                        "type": "string"
                    },
                    "cpf": {
                        "description": "Documento de identificação do paciente - CPF",
                        "type": "string"
                    },
                    "phone_number": {
                        "description": "Número de telefone do paciente para contato",
                        "type": "string"
                    },
                    "birthdate": {
                        "format": "date",
                        "description": "Data de nascimento do paciente",
                        "type": "string"
                    },
                    "height": {
                        "$ref": "#/components/schemas/Height",
                        "description": "Altura do paciente",
                        "properties": {
                            "value": {
                                "format": "double",
                                "type": "number"
                            },
                            "unit": {
                                "type": "string"
                            }
                        }
                    },
                    "weight": {
                        "$ref": "#/components/schemas/Weight",
                        "description": "Peso do paciente",
                        "properties": {
                            "value": {
                                "format": "int32",
                                "type": "integer"
                            },
                            "unit": {
                                "type": "string"
                            }
                        }
                    },
                    "smoker": {
                        "description": "Indica se o paciente é fumante (true-Sim, false-Não)",
                        "type": "boolean"
                    },
                    "comorbidities": {
                        "description": "Lista de comorbidades que afetam o paciente (caso tenha)",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "medical_insurance": {
                        "$ref": "#/components/schemas/MedicalInsurance",
                        "description": "Plano de saúde na qual o paciente está inscrito",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "operator_code": {
                                "type": "string"
                            }
                        }
                    },
                    "address": {
                        "$ref": "#/components/schemas/Address",
                        "description": "Endereço residencial do paciente",
                        "properties": {
                            "street": {
                                "type": "string"
                            },
                            "complement": {
                                "type": "string"
                            },
                            "district": {
                                "type": "string"
                            },
                            "city": {
                                "type": "string"
                            },
                            "state": {
                                "type": "string"
                            },
                            "zipcode": {
                                "type": "string"
                            }
                        }
                    }
                },
                "example": {
                    "name": "Marcio Andrade",
                    "cpf": "123.345.789-0",
                    "phone_number": "11-91111-4394",
                    "birthdate": "2001-08-10",
                    "height": {
                        "value": 1.78,
                        "unit": "m"
                    },
                    "weight": {
                        "value": 80,
                        "unit": "kg"
                    },
                    "smoker": false,
                    "comorbidities": [
                        "Cirrose hepática",
                        "Valvopatia"
                    ],
                    "medical_insurance": {
                        "id": "324.5231100.3432",
                        "operator_code": "AMIL"
                    },
                    "address": {
                        "street": "Rua Luis Gois, 1200",
                        "complement": "apto 204",
                        "district": "Vila Mariana",
                        "city": "São Paulo",
                        "state": "SP",
                        "zipcode": "04043-050"
                    }
                }
            },
            "PatientsRequestPatch": {
                "title": "Root Type for PatientsResponse",
                "description": "Representa um paciente da clínica - utilizado no request de alteração do objeto de instância (específico para operação PATCH)",
                "required": [],
                "type": "object",
                "properties": {
                    "name": {
                        "description": "Nome completo do paciente",
                        "type": "string"
                    },
                    "cpf": {
                        "description": "Documento de identificação do paciente - CPF",
                        "type": "string"
                    },
                    "phone_number": {
                        "description": "Número de telefone do paciente para contato",
                        "type": "string"
                    },
                    "birthdate": {
                        "format": "date",
                        "description": "Data de nascimento do paciente",
                        "type": "string"
                    },
                    "height": {
                        "$ref": "#/components/schemas/Height",
                        "description": "Altura do paciente",
                        "properties": {
                            "value": {
                                "format": "double",
                                "type": "number"
                            },
                            "unit": {
                                "type": "string"
                            }
                        }
                    },
                    "weight": {
                        "$ref": "#/components/schemas/Weight",
                        "description": "Peso do paciente",
                        "properties": {
                            "value": {
                                "format": "int32",
                                "type": "integer"
                            },
                            "unit": {
                                "type": "string"
                            }
                        }
                    },
                    "smoker": {
                        "description": "Indica se o paciente é fumante (true-Sim, false-Não)",
                        "type": "boolean"
                    },
                    "comorbidities": {
                        "description": "Lista de comorbidades que afetam o paciente (caso tenha)",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "medical_insurance": {
                        "$ref": "#/components/schemas/MedicalInsurance",
                        "description": "Plano de saúde na qual o paciente está inscrito",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "operator_code": {
                                "type": "string"
                            }
                        }
                    },
                    "address": {
                        "$ref": "#/components/schemas/Address",
                        "description": "Endereço residencial do paciente",
                        "properties": {
                            "street": {
                                "type": "string"
                            },
                            "complement": {
                                "type": "string"
                            },
                            "district": {
                                "type": "string"
                            },
                            "city": {
                                "type": "string"
                            },
                            "state": {
                                "type": "string"
                            },
                            "zipcode": {
                                "type": "string"
                            }
                        }
                    }
                },
                "example": {
                    "name": "Marcio Andrade",
                    "cpf": "123.345.789-0",
                    "phone_number": "11-91111-4394",
                    "birthdate": "2001-08-10",
                    "height": {
                        "value": 1.78,
                        "unit": "m"
                    },
                    "weight": {
                        "value": 80,
                        "unit": "kg"
                    },
                    "smoker": false,
                    "comorbidities": [
                        "Cirrose hepática",
                        "Valvopatia"
                    ],
                    "medical_insurance": {
                        "id": "324.5231100.3432",
                        "operator_code": "AMIL"
                    },
                    "address": {
                        "street": "Rua Luis Gois, 1200",
                        "complement": "apto 204",
                        "district": "Vila Mariana",
                        "city": "São Paulo",
                        "state": "SP",
                        "zipcode": "04043-050"
                    }
                }
            },
            "ErrorMessage": {
                "title": "Root Type for ErrorMessage",
                "description": "Mensagem de erro a ser retornada no body do response",
                "required": [
                    "description",
                    "field",
                    "issue"
                ],
                "type": "object",
                "properties": {
                    "issue": {
                        "description": "Código identificador específico para o cenário de erro",
                        "type": "string"
                    },
                    "description": {
                        "description": "Descrição do erro",
                        "type": "string"
                    },
                    "location": {
                        "description": "Localização do campo que causou o erro",
                        "type": "string"
                    },
                    "field": {
                        "description": "Nome do campo que causou o erro",
                        "type": "string"
                    },
                    "value": {
                        "description": "Valor do campo que causou o erro",
                        "type": "string"
                    }
                },
                "example": {
                    "issue": "INVALID_PARAMETER_VALUE",
                    "description": "Field value is invalid",
                    "location": "body",
                    "field": "cpf",
                    "value": "000.000.000-00"
                }
            }
        },
        "responses": {
            "PatientsResponse": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/PatientsResponse"
                        },
                        "examples": {
                            "PatientsResponseExample": {
                                "value": {
                                    "id": "3dc97efc-1b5b-492c-905c-449677b390e1",
                                    "name": "Marcio Andrade",
                                    "cpf": "123.345.789-0",
                                    "phone_number": "11-91111-4394",
                                    "birthdate": "2001-08-10",
                                    "height": {
                                        "value": 1.78,
                                        "unit": "m"
                                    },
                                    "weight": {
                                        "value": 80,
                                        "unit": "kg"
                                    },
                                    "smoker": false,
                                    "comorbidities": [
                                        "Cirrose hepática",
                                        "Valvopatia"
                                    ],
                                    "medical_insurance": {
                                        "id": "324.5231100.3432",
                                        "operator_code": "AMIL"
                                    },
                                    "address": {
                                        "street": "Rua Luis Gois, 1200",
                                        "complement": "apto 204",
                                        "district": "Vila Mariana",
                                        "city": "São Paulo",
                                        "state": "SP",
                                        "zipcode": "04043-050"
                                    }
                                }
                            }
                        }
                    }
                },
                "description": "Representa um paciente da clínica - utilizado no response da consulta do objeto de instância"
            },
            "PatientsResponseList": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/components/schemas/PatientsResponseList"
                            }
                        },
                        "examples": {
                            "PatientsResponseListExample": {
                                "value": [
                                    {
                                        "id": "3dc97efc-1b5b-492c-905c-449677b390e1",
                                        "name": "Marcio Andrade",
                                        "cpf": "123.345.789-0"
                                    },
                                    {
                                        "id": "9ed9bf5b-2a3b-4f07-b908-981291d30965",
                                        "name": "Sarah Gomes Correia",
                                        "cpf": "788.205.510-71"
                                    },
                                    {
                                        "id": "920d5b83-89a9-4408-bd5d-c978c4eb78e3",
                                        "name": "Flavio Felipe Inacio",
                                        "cpf": "737.775.330-76"
                                    },
                                    {
                                        "id": "17d4eae8-ff5e-4081-9ef1-c7d8d4c9c051",
                                        "name": "Simone Maria dos Santos",
                                        "cpf": "917.010.320-82"
                                    },
                                    {
                                        "id": "899a8ccf-9a6f-45f1-9277-9326c788378f",
                                        "name": "Ronaldo de Souza Oliveira",
                                        "cpf": "772.744.020-56"
                                    },
                                    {
                                        "id": "415bfbb1-4620-44b6-b05c-75c2da38a0db",
                                        "name": "Rita Vieira da Rosa",
                                        "cpf": "605.666.270-51"
                                    },
                                    {
                                        "id": "31401738-0d60-47e3-90c7-a296aea6e85b",
                                        "name": "Juliana Ventura Fernandes",
                                        "cpf": "361.386.640-43"
                                    }
                                ]
                            }
                        }
                    }
                },
                "description": "Representa um paciente da clínica - utilizado no response da consulta do objeto de coleção"
            }
        }
    }
}