{
    "openapi": "3.0.2",
    "info": {
        "title": "Consultas",
        "version": "1.0.0",
        "description": "ProHealth - Contrato da API de consultas médicas"
    },
    "servers": [
        {
            "url": "http://localhost:8080",
            "description": ""
        }
    ],
    "paths": {
        "/v1/appointments/{id}": {
            "summary": "Rota de consultas médicos",
            "description": "Este recurso é a representação da lista de consultas médicos da clínica",
            "get": {
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/AppointmentResponse"
                    }
                },
                "summary": "Operação de Consultas médicas",
                "description": "Operação utilizada para obter uma consulta médica marcada"
            },
            "parameters": [
                {
                    "name": "id",
                    "description": "Campo identificador da consulta médico",
                    "schema": {
                        "type": "string"
                    },
                    "in": "path",
                    "required": true
                }
            ]
        }
    },
    "components": {
        "schemas": {
            "Patient": {
                "title": "Root Type for Patient",
                "description": "Objeto que representa um paciente da clínica",
                "required": [
                    "cpf",
                    "id",
                    "name",
                    "phone_number"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "description": "Código identificador do paciente",
                        "type": "string"
                    },
                    "name": {
                        "description": "Nome completo do paciente",
                        "type": "string"
                    },
                    "cpf": {
                        "description": "Documento de identificação do paciente - CPF",
                        "type": "string"
                    },
                    "phone_number": {
                        "description": "Número de telefone do paciente",
                        "type": "string"
                    }
                },
                "example": {
                    "id": "3dc97efc-1b5b-492c-905c-449677b390e1",
                    "name": "Marcio Andrade",
                    "cpf": "123.345.789-0",
                    "phone_number": "11-91111-4394"
                }
            },
            "Doctor": {
                "title": "Root Type for Doctor",
                "description": "Objeto que representa um médico da clínica",
                "required": [
                    "crm",
                    "id",
                    "name",
                    "phone_number"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "description": "Código identificador do médico",
                        "type": "string"
                    },
                    "name": {
                        "description": "Nome completo do médico",
                        "type": "string"
                    },
                    "crm": {
                        "description": "Registro no Conselho Regional de Medicina",
                        "type": "string"
                    },
                    "phone_number": {
                        "description": "Número de telefone do médico",
                        "type": "string"
                    }
                },
                "example": {
                    "id": "44ce5e16-0acf-4b21-91aa-f8610f247cbb",
                    "name": "José Eduardo Sousa",
                    "crm": "008.321.111-0",
                    "phone_number": "(11)92222-5501"
                }
            },
            "AppointmentResponse": {
                "title": "Root Type for AppointmentResponse",
                "description": "Objeto que representa uma consulta marcada",
                "required": [
                    "doctor",
                    "id",
                    "patient",
                    "scheduled_at"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "description": "Código identificador da consulta",
                        "type": "string"
                    },
                    "scheduled_at": {
                        "format": "date-time",
                        "description": "Data/hora agendada para a consulta",
                        "type": "string"
                    },
                    "patient": {
                        "$ref": "#/components/schemas/Patient",
                        "description": "Paciente atendido na consulta",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "cpf": {
                                "type": "string"
                            },
                            "phone_number": {
                                "type": "string"
                            }
                        }
                    },
                    "doctor": {
                        "$ref": "#/components/schemas/Doctor",
                        "description": "Médico que atende a consulta",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "crm": {
                                "type": "string"
                            },
                            "phone_number": {
                                "type": "string"
                            }
                        }
                    }
                },
                "example": {
                    "id": "ba20f18f-4797-4e39-8502-e63be9929b96",
                    "scheduled_at": "2020-12-23T07:23:00Z",
                    "patient": {
                        "id": "3dc97efc-1b5b-492c-905c-449677b390e1",
                        "name": "Marcio Andrade",
                        "cpf": "123.345.789-0",
                        "phone_number": "11-91111-4394"
                    },
                    "doctor": {
                        "id": "44ce5e16-0acf-4b21-91aa-f8610f247cbb",
                        "name": "José Eduardo Sousa",
                        "crm": "008.321.111-0",
                        "phone_number": "(11)92222-5501"
                    }
                }
            }
        },
        "responses": {
            "AppointmentResponse": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/AppointmentResponse"
                        },
                        "examples": {
                            "AppointmentExample": {
                                "value": {
                                    "id": "ba20f18f-4797-4e39-8502-e63be9929b96",
                                    "scheduled_at": "2020-12-23T07:23:00Z",
                                    "patient": {
                                        "id": "3dc97efc-1b5b-492c-905c-449677b390e1",
                                        "name": "Marcio Andrade",
                                        "cpf": "123.345.789-0",
                                        "phone_number": "11-91111-4394"
                                    },
                                    "doctor": {
                                        "id": "44ce5e16-0acf-4b21-91aa-f8610f247cbb",
                                        "name": "José Eduardo Sousa",
                                        "crm": "008.321.111-0",
                                        "phone_number": "(11)92222-5501"
                                    }
                                }
                            }
                        }
                    }
                },
                "description": "Entidade de consulta médica retornada no response"
            }
        }
    }
}